### PR TITLE
Makefile: Compile omsMAXv.cpp only under vxWorks/Linux

### PR DESCRIPTION
**Pull request by tboegi**

### CODE REVIEW

**Comment by kmpeters** [comment]
I think this would result in build errors on platforms other than Linux and VxWorks because the registrar line for the MAXv call is included by default:
https://github.com/epics-motor/motorOmsAsyn/blob/4fdd003bcede7728327026525ad633beab6cfcaf/omsAsynApp/src/Makefile#L10
https://github.com/epics-motor/motorOmsAsyn/blob/4fdd003bcede7728327026525ad633beab6cfcaf/omsAsynApp/src/omsAsynSupport.dbd#L2
But I haven't had a chance to confirm that yet.

**Comment by tboegi** [comment]
Actually, the OmsAsyn module compiles under Windows & Mac:
https://travis-ci.com/github/tboegi/motor/builds/153028075?utm_medium=notification&utm_source=email

The omsAsyn is compiled, e.g.
modules/motorOmsAsyn/omsAsynApp/src/omsMAXnet.cpp
is part of the build.

We just skip omsMAXv.cpp under not-Linux/vxWorks.
What is about RTEMS ?

**Comment by kmpeters** [comment]
> What is about RTEMS ?

I would expect someone running RTEMS will want to use this support in the future.  I would build for it, if the build isn't broken.

**Comment by tboegi** [comment]
See next PR

**Pull request closed without merging**
